//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPract2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string OrderDate { get; set; }
        public string DeliveryDate { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> PriceInOrder { get; set; }
        public Nullable<double> LineTotal { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Products Products { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
