//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPract2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public string Background
        {
            get
            {
                if (DiscountProcent > 10)
                    return "#BB5FCA";
                else
                    return "White";
            }
        }
        public Products()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string Description { get; set; }
        public string Composition { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> DiscountProcent { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<double> MinStock { get; set; }
        public Nullable<double> QuantityInStock { get; set; }
        public string Image { get; set; }
    
        public virtual Discounts Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
